{
    "openapi": "3.0.1",
    "info": {
        "title": "Tasks",
        "description": "",
        "version": "v3",
        "x-hubspot-product-tier-requirements": {
            "marketing": "FREE",
            "sales": "FREE",
            "service": "FREE",
            "cms": "FREE"
        },
        "x-hubspot-documentation-banner": "NONE",
        "x-hubspot-api-use-case": "If you're using a third-party service for project management, you can create and manage any tasks associated with your CRM records by logging them in HubSpot.",
        "x-hubspot-related-documentation": [
            {
                "name": "Tasks Guide",
                "url": "https://developers.hubspot.com/docs/guides/api/crm/engagements/tasks"
            }
        ],
        "x-hubspot-introduction": "Use the tasks API to associate tasks with your CRM records. You can assign tasks to specific users in your account, keep track of their status, and organize them using different priorities and types."
    },
    "servers": [
        {
            "url": "https://api.hubapi.com/crm/v3/objects/tasks"
        }
    ],
    "tags": [
        {
            "name": "Batch"
        },
        {
            "name": "Basic"
        },
        {
            "name": "Search"
        }
    ],
    "paths": {
        "/batch/read": {
            "post": {
                "tags": [
                    "Batch"
                ],
                "summary": "Read tasks by ID or property",
                "description": "Retrieves a batch of tasks based on the `inputs`, `properties`, and `propertiesWithHistory` fields. The `properties` field lists properties to return, while the `propertiesWithHistory` field includes properties with their previous values. If any specified properties are missing from the requested objects, they will be ignored.",
                "operationId": "post-/crm/v3/objects/tasks/batch/read_read",
                "security": [
                    {
                        "oauth2": [
                            "crm.objects.contacts.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.contacts.read"
                        ]
                    }
                ]
            }
        },
        "/{taskId}": {
            "get": {
                "tags": [
                    "Basic"
                ],
                "summary": "Read a task",
                "description": "Read an Object identified by `{taskId}`. `{taskId}` refers to the internal object ID by default, or optionally any unique property value as specified by the `idProperty` query param.  Control what is returned via the `properties` query param.",
                "operationId": "get-/crm/v3/objects/tasks/{taskId}_getById",
                "security": [
                    {
                        "oauth2": [
                            "crm.objects.contacts.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.contacts.read"
                        ]
                    }
                ]
            },
            "delete": {
                "tags": [
                    "Basic"
                ],
                "summary": "Archive a task",
                "description": "Move an Object identified by `{taskId}` to the recycling bin.",
                "operationId": "delete-/crm/v3/objects/tasks/{taskId}_archive",
                "security": [
                    {
                        "oauth2": [
                            "crm.objects.contacts.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.contacts.write"
                        ]
                    }
                ]
            },
            "patch": {
                "tags": [
                    "Basic"
                ],
                "summary": "Update a task",
                "description": "Perform a partial update of an Object identified by `{taskId}`. `{taskId}` refers to the internal object ID by default, or optionally any unique property value as specified by the `idProperty` query param. Provided property values will be overwritten. Read-only and non-existent properties will be ignored. Properties values can be cleared by passing an empty string.",
                "operationId": "patch-/crm/v3/objects/tasks/{taskId}_update",
                "security": [
                    {
                        "oauth2": [
                            "crm.objects.contacts.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.contacts.write"
                        ]
                    }
                ]
            }
        },
        "/batch/archive": {
            "post": {
                "tags": [
                    "Batch"
                ],
                "summary": "Archive a batch of tasks by ID",
                "description": "Moves a batch of tasks identified by the `id` s specified in the `inputs` to the recycling bin.",
                "operationId": "post-/crm/v3/objects/tasks/batch/archive_archive",
                "security": [
                    {
                        "oauth2": [
                            "crm.objects.contacts.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.contacts.write"
                        ]
                    }
                ]
            }
        },
        "/batch/create": {
            "post": {
                "tags": [
                    "Batch"
                ],
                "summary": "Create a batch of tasks",
                "description": " Create a batch of tasks using the same rules as when creating an individual task",
                "operationId": "post-/crm/v3/objects/tasks/batch/create_create",
                "security": [
                    {
                        "oauth2": [
                            "crm.objects.contacts.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.contacts.write"
                        ]
                    }
                ]
            }
        },
        "/batch/update": {
            "post": {
                "tags": [
                    "Batch"
                ],
                "summary": "Update tasks by ID or property",
                "description": "update records identified by a unique property value as specified by the `idProperty` query param. `idProperty` query param refers to a property whose values are unique for the object.",
                "operationId": "post-/crm/v3/objects/tasks/batch/update_update",
                "security": [
                    {
                        "oauth2": [
                            "crm.objects.contacts.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.contacts.write"
                        ]
                    }
                ]
            }
        },
        "/": {
            "get": {
                "tags": [
                    "Basic"
                ],
                "summary": "List of the tasks",
                "description": "Read a page of tasks. Control what is returned via the `properties` query param.",
                "operationId": "get-/crm/v3/objects/tasks_getPage",
                "security": [
                    {
                        "oauth2": [
                            "crm.objects.contacts.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.contacts.read"
                        ]
                    }
                ]
            },
            "post": {
                "tags": [
                    "Basic"
                ],
                "summary": "Create a task",
                "description": "Create a task with the given properties and return a copy of the object, including the ID. Documentation and examples for creating standard tasks is provided.",
                "operationId": "post-/crm/v3/objects/tasks_create",
                "security": [
                    {
                        "oauth2": [
                            "crm.objects.contacts.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.contacts.write"
                        ]
                    }
                ]
            }
        },
        "/batch/upsert": {
            "post": {
                "tags": [
                    "Batch"
                ],
                "summary": "Upsert a batch of tasks",
                "description": "Create or update records identified by a unique property value as specified by the `idProperty` query param. `idProperty` query param refers to a property whose values are unique for the object.",
                "operationId": "post-/crm/v3/objects/tasks/batch/upsert_upsert",
                "security": [
                    {
                        "oauth2": [
                            "crm.objects.contacts.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.contacts.write"
                        ]
                    }
                ]
            }
        },
        "/search": {
            "post": {
                "tags": [
                    "Search"
                ],
                "summary": "Search for tasks",
                "description": "Search for tasks based on filters, properties, sorting, and query parameters.",
                "operationId": "post-/crm/v3/objects/tasks/search_doSearch",
                "security": [
                    {
                        "oauth2": [
                            "crm.objects.contacts.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.contacts.read"
                        ]
                    }
                ],
                "x-hubspot-rate-limit-exemptions": [
                    "ten-secondly"
                ]
            }
        }
    },
    "components": {
        "securitySchemes": {
            "oauth2_legacy": {
                "type": "oauth2",
                "flows": {
                    "authorizationCode": {
                        "authorizationUrl": "https://app.hubspot.com/oauth/authorize",
                        "tokenUrl": "https://api.hubapi.com/oauth/v1/token",
                        "scopes": {
                            "e-commerce": "e-commerce",
                            "crm.objects.custom.write": "Change custom object records",
                            "media_bridge.read": "Read media and media events",
                            "crm.objects.goals.read": "Read goals",
                            "tickets": "Read and write tickets",
                            "crm.objects.custom.read": "View custom object records"
                        }
                    }
                }
            },
            "oauth2": {
                "type": "oauth2",
                "flows": {
                    "authorizationCode": {
                        "authorizationUrl": "https://app.hubspot.com/oauth/authorize",
                        "tokenUrl": "https://api.hubapi.com/oauth/v1/token",
                        "scopes": {
                            "crm.objects.contacts.read": " ",
                            "crm.objects.listings.read": "Read listings",
                            "crm.objects.carts.write": "Write cart",
                            "crm.objects.courses.write": "Write courses",
                            "crm.objects.quotes.write": "Quotes",
                            "crm.objects.users.read": "Read User CRM objects",
                            "crm.objects.companies.read": " ",
                            "crm.objects.appointments.read": "Read appointments",
                            "crm.objects.partner-clients.write": "Modify Partner Client CRM objects",
                            "crm.objects.leads.read": "Read lead objects",
                            "crm.objects.appointments.write": "Write appointments",
                            "crm.objects.services.write": "Write services",
                            "crm.objects.line_items.read": "Line Items",
                            "crm.objects.courses.read": "Read courses",
                            "crm.objects.deals.read": " ",
                            "crm.objects.invoices.read": "Read invoices objects",
                            "crm.objects.partner-clients.read": "View Partner Client CRM objects",
                            "crm.objects.deals.write": " ",
                            "crm.objects.line_items.write": "Line Items",
                            "crm.objects.listings.write": "Write listings",
                            "crm.objects.companies.write": " ",
                            "crm.objects.contacts.write": " ",
                            "crm.objects.users.write": "Write User CRM objects",
                            "crm.objects.commercepayments.read": "Read the COMMERCE_PAYMENT object.",
                            "crm.objects.leads.write": "Modify lead objects",
                            "crm.objects.subscriptions.read": "Read Commerce Subscriptions",
                            "crm.objects.carts.read": "Read carts",
                            "crm.objects.orders.write": "Write orders",
                            "crm.objects.quotes.read": "Quotes",
                            "crm.objects.services.read": "Read services",
                            "crm.objects.orders.read": "Read Orders"
                        }
                    }
                }
            },
            "private_apps_legacy": {
                "type": "apiKey",
                "name": "private-app-legacy",
                "in": "header",
                "x-ballerina-name": "privateAppLegacy"
            },
            "private_apps": {
                "type": "apiKey",
                "name": "private-app",
                "in": "header",
                "x-ballerina-name": "privateApp"
            }
        }
    },
    "x-hubspot-available-client-libraries": [
        "PHP",
        "Node",
        "Ruby",
        "Python"
    ],
    "x-hubspot-product-tier-requirements": {
        "marketing": "FREE",
        "sales": "FREE",
        "service": "FREE",
        "cms": "FREE"
    },
    "x-hubspot-documentation-banner": "NONE"
}